# ./docker-compose.yml
services:
  postgres:
    image: postgres:16
    container_name: fs3m_postgres
    environment:
      POSTGRES_DB: fs3m
      POSTGRES_USER: fs3m_user
      POSTGRES_PASSWORD: fs3m_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fs3m_user -d fs3m"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  default:
    name: fs3m_net

volumes:
  postgres_data:
