# Generated by Django 5.0.6 on 2025-08-09 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("frameworks", "0002_alter_choiceoption_weight"),
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="frameworks.framework",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="responses.submission",
                    ),
                ),
                (
                    "assessment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.assessmenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("FUNCTION", "Function"),
                            ("CATEGORY", "Category"),
                            ("CONTROL", "Control"),
                        ],
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("order", models.IntegerField(default=0)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buckets",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "unique_together": {("assessment", "level", "code")},
                "index_together": {("assessment", "level", "code")},
            },
        ),
        migrations.CreateModel(
            name="FrameworkAssessmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mapping", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=True)),
                (
                    "assessment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.assessmenttype",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frameworks.framework",
                    ),
                ),
            ],
            options={
                "unique_together": {("framework", "assessment_type")},
            },
        ),
    ]
