# Generated by Django 5.0.6 on 2025-08-08 23:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="formularios_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                help_text="Lista de IDs de formulários que este cliente pode acessar.",
                size=None,
                verbose_name="IDs de Formulários Permitidos (Cliente)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gestor_referente",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "gestor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analistas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gestor Referente (para Analista)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA habilitado"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_backup_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                help_text="Códigos de uso único para recuperação (opcional).",
                null=True,
                size=None,
                verbose_name="Códigos de backup 2FA",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_secret",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Segredo TOTP"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "cliente"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subclientes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cliente Associado (para Subcliente)",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("cliente", "Cliente"),
                    ("subcliente", "Subcliente"),
                    ("analista", "Analista"),
                    ("gestor", "Gestor"),
                ],
                default="cliente",
                max_length=50,
            ),
        ),
    ]
