# Generated by Django 5.0.6 on 2025-08-09 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_formularios_ids_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("activate", "Activate"),
                            ("deactivate", "Deactivate"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("enable_2fa", "Enable 2Fa"),
                            ("disable_2fa", "Disable 2Fa"),
                            ("generate_report", "Generate Report"),
                            ("view_report", "View Report"),
                            ("delete_report", "Delete Report"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="users_usera_action_d9cb85_idx",
                    ),
                    models.Index(
                        fields=["target_user", "created_at"],
                        name="users_usera_target__6c530c_idx",
                    ),
                ],
            },
        ),
    ]
