# Generated by Django 5.0.6 on 2025-08-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScoringModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("mapping", models.JSONField(default=dict)),
                ("rules", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(default="1.0", max_length=32)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "editable",
                    models.BooleanField(
                        default=False,
                        help_text="If true, allow editing this framework (controls/questions) via UI.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug", "version"],
                "unique_together": {("slug", "version")},
            },
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("editable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="frameworks.framework",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "version"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="frameworks.domain",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="frameworks.framework",
                    ),
                ),
            ],
            options={
                "ordering": ["framework", "parent__id", "order", "id"],
                "unique_together": {("framework", "code")},
            },
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="frameworks.domain",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="frameworks.framework",
                    ),
                ),
                (
                    "scoring_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controls",
                        to="frameworks.scoringmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["framework", "domain", "order", "code"],
                "unique_together": {("framework", "code")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_code", models.CharField(blank=True, default="", max_length=50)),
                ("prompt", models.CharField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Yes/No"),
                            ("single", "Single choice"),
                            ("multiple", "Multiple choice"),
                            ("scale", "Scale"),
                            ("json", "JSON blob"),
                            ("file", "File placeholder (store metadata elsewhere)"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="frameworks.control",
                    ),
                ),
                (
                    "scoring_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="frameworks.scoringmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["control", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=100)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="frameworks.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_items",
                        to="frameworks.control",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_items",
                        to="frameworks.question",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="frameworks.formtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "order", "id"],
                "unique_together": {("template", "control", "question")},
            },
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="templates",
                through="frameworks.TemplateItem",
                to="frameworks.control",
            ),
        ),
        migrations.CreateModel(
            name="ControlMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings_origin",
                        to="frameworks.control",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings_target",
                        to="frameworks.control",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["origin"], name="frameworks__origin__e7c77c_idx"
                    ),
                    models.Index(
                        fields=["target"], name="frameworks__target__c34795_idx"
                    ),
                ],
                "unique_together": {("origin", "target")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="formtemplate",
            unique_together={("slug", "version")},
        ),
    ]
