# Generated by Django 5.0.6 on 2025-08-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choiceoption",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
